name: Assign Issue
on:
  issue_comment:
    types:
      - created
jobs:
  assign_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/take' }}
    steps:
      - uses: actions/checkout@v2
      - name: Assign issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login }}
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee "${{ github.event.comment.user.login }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
